--- #file
- hosts: webservers
  become: yes
  user: ansible
  connection: ssh 
  tasks:
    - name: create file
     #file: path=/tmp/shaan state=touch
     #file: path=/tmp/shaan state=directory
      file:       #to change permissions of already existing file
        path: /etc/aru
        owner: ansible
        group: foo
        mode: '0644'


        # value of state must be one of: absent, directory, file, hard, link, touch, got: present"}

